#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m config window-placement second_child


#padding
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0 
yabai -m config right_padding 0 
yabai -m config window_gap 3 

# mouse settings

yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier alt
# left click + drag
yabai -m config mouse_action1 move
# right click + drag
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap


# Disable specific apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Slack$" display=2 manage=off
yabai -m rule --add app="econ-calendar" display=2 manage=off
yabai -m rule --add app="deadlink" display=2
yabai -m rule --add app="app" display=2



yabai -m rule --apply


yabai -m config external_bar all:0:0
